= A metadata convention for processed acoustic data from active acoustic systems
:imagesdir: images\
:toc: preamble
:toclevels: 4
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


This repository contains the text and source files necessary to generate _A metadata convention for processed acoustic data from active acoustic systems_ (link:docs/acmeta.adoc[AcMeta]), and is where new versions of the convention are discussed and developed.


Version 1.10 of the AcMeta convention (as ICES SISP 4-TG-AcMeta) is available https://www.ices.dk/sites/pub/Publication%20Reports/ICES%20Survey%20Protocols%20(SISP)/SISP-4%20A%20metadata%20convention%20for%20processed%20acoustic%20data%20from%20active%20acoustic%20systems.pdf[here]. Previous published versions were 1.0 (2013) and 1.05 (2014).

== Preview of the current working draft
The current working draft of the acoustic metadata convention is in the `Formatted_docs` folder as an HTML file. To view a rendering of convention in your web browser, please go https://gitcdn.link/repo/ices-publications/AcMeta/master/Formatted_docs/TG-AcMeta.html[here] (note that this can be up to two hours out-of-date).

image:https://github.com/ices-publications/AcMeta/workflows/BuildDocuments/badge.svg[]

== Suggestions and contributions welcome
WGFAST welcomes suggestions, discussion, and contributions to this metadata convention.

Before submitting a pull request, please take a moment to find out whether your idea fits within the scope and aims of the convention, and whether your idea can be achieved within the existing metadata convention. It is your role to adequately explain and justify the merits of what you want. Please provide as much detail and context as possible. Good pull requests remain focused in scope and avoid containing unrelated commits.

*Please ask the convention coordinators before starting on any _significant_ edits*. Otherwise you risk spending a lot of time working on something that the convention coordinators might not want to merge into the project.


== How to contribute
The metadata convention is written in AsciiDoc markup language. Suggestions, discussions, and contributions are done through the facilities provided by GitHub. Please use the https://github.com/ices-publications/AcMeta/issues[issue tracker] for suggestions and discussions, and create https://github.com/ices-publications/AcMeta/issues[pull requests] for contributions.

For guidance on Git, GitHub, and AsciiDoc syntax, as well as the suggested Git workflow for contributors, please refer to documents in the https://github.com/ices-eg/wg_WGFAST/tree/master/How_to_contribute[How to contribute] folder in the `ices-eg/wg_WGFAST` repository.
